---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-homelab-ca
  namespace: hbr-keycloak
spec:
  isCA: false
  secretName: keycloak-server-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - FtsCoDe-de
    organizationalUnits:
      - Homelab
    countries:
      - DE
    provinces:
      - NRW
    localities:
      - Stuttgart
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  commonName: "keycloak.homelab.ftscode.de"
  dnsNames:
    - "keycloak.homelab.ftscode.de"
  issuerRef:
    name: keycloak-ca-issuer
    kind: Issuer