---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: info@ftscode.de
    privateKeySecretRef:
      name: letsencrypt-production-key
    solvers:
    - dns01:
        cloudflare:
          email: fkheinstein@gmail.com
          apiTokenSecretRef:
            name: cloudflare-token-secret
            key: api-token
      selector:
        dnsZones:
          - prod.ftscode.de
          - ftscode.de