repo:
  url: https://github.com/fkheinstein204/k8s-homelab.git
  revision: main


applications:

  - name: grafana
    namespace: grafana
    path: monitoring/prod-cluster/grafana
    manifest-paths: /monitoring/prod-cluster/grafana
    sync-wave: "-3"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true



  - name: influxdb
    namespace: influxdb
    path: monitoring/prod-cluster/influxdb
    manifest-paths: /monitoring/prod-cluster/influxdb
    sync-wave: "-3"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

