repo:
  url: https://github.com/fkheinstein204/k8s-homelab.git
  revision: main


applications:

  - name: metrics-server
    namespace: kube-system
    path: monitoring/prod-cluster/metrics-server
    manifest-paths: /monitoring/prod-cluster/metrics-server
    sync-wave: "-1"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

