vault:
  server:
    extraEnvVars:
      - name: LOG_LEVEL
        value: trace

    ha:
      enabled: true
      replicas: 3
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi 

