traefik:

  ingressRoute:
    dashboard:
      enabled: true

  logs:
    general:
      level: DEDUB
    access:
      enabled: true

  tlsStore:
    default:
      defaultCertificate:
        secretName: wildcard-homelab-ftscode-de-prod-tls