repo:
  url: https://github.com/fkheinstein204/k8s-homelab.git
  revision: main


applications:

  - name: mariadb
    namespace: database
    path: database/mariadb
    manifest-paths: /database/mariadb
    sync-wave: "-1"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

  - name: postgresql
    namespace: database
    path: database/postgresql
    manifest-paths: /database/postgresql
    sync-wave: "-1"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true


  - name: redis
    namespace: database
    path: database/redis
    manifest-paths: /database/redis
    sync-wave: "-1"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true