argocd:
  global:
    domain: argocd.homelab.ftscode.de

  dex:
    enabled: false




  configs:
    params:
      server.insecure: true

    cm:
      timeout.reconciliation: 60s

  server:
    # -- The number of server pods to run
    replicas: 2

    logLevel: debug

    metrics:
      enabled: true

    extraArgs:
      - "--insecure"

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        cert-manager.io/common-name: "argocd.homelab.ftscode.de"
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      extraTls:
        - hosts:
            - argocd.homelab.ftscode.de
          secretName: argocd-cert

    resources:
      requests:
        cpu: 50m
        memory: 64Mi

  repoServer:
    metrics:
      enabled: true