---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-http-ingress-route
  namespace: grafana
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`grafana.homelab.ftscode.de`)
      services:
        - name: grafana
          port: 80