---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: database
spec:
  encryptedData:
    postgres-password: AgB4t1CJpL4IPtj0L0vmdvy+rc25PV6T4J2SjPI13LfKC+HLNbUAMjsgvQmyEl2Seuix2oVAM31i5tv3X784wbRmXgwG2X31gh64OzW2bG67W+hb9SOD9kB9AOcOz+23lPjftO0wlvli5MgIJHwPmsFcv3Alm2+j0hX4GCSvU3PgLVLFE6c7omfHMJ3NYr2GSjQWShxZgEp8YPb2D0EwGGrFXcivgmQLwLA5Dxar6UmKJqmzOc+qQwG3d7wO51JXDUTBH0V4FaPGooIIuIUfl7r7kVyL10jL8WERU3ZMSK7PGZyc6xrotCIYGElecv8RjaDZiISDNpWEYOI17n78SnvN+wnuKL+OBzs6fkjyDKO3h1ZOE/uqIw0pVKePyA9rhTeWGtlQ44QU2Ze3vkLrXMdqJhx8o16SbnHoaOZ9MAQkpP9N96e2XJ+j+OOs/tMW1mB8h91YAVFbV2a9aZO2sVVh0CeKvHKUszP9IEtEng1yyepZYXL4WHYMLEZNrGh30F78FKU9gR5qHGZrZzHiO4ZGBYacVt7pPpMh0UIcCDHtMconUzycPvh+qyxx/L3FuUg07yCNK87EGFIJxBcfTFNpFSWvdoPSel8O/0WtUzF3XEoVSKsRgEwwKLb7r4hkQvLmj8OOOLC0I0A94ivvDHdA7hSznwnafhUblxale9y8tc31sonLXK4xx6z/+0/7wTiS0gpFjoheBV5vgPn0P9akEUgNqqAixI/kK4AS4rRFtDNu+1UECRtnq1qDZw==
    replication-password: AgALd4MBnj3sPssf53YCA/YJZoAqye3vV4DNiwA63CBMQJYRbfBxeLJRFlYp/UmRwfYw66gDbXgcTDitB5pGxm99OrLJHOGZWAIQDripMAikN+vY9i2seTlmxXe3lXjE+g4ThdGmsq6yS+5pQ85tJ8ncf8MWw5xeK4yAKYHVQYclm7vBy3SWe9r98/sVN0M+af+wbtLUh/1mV506JyBsNk1RrepOMIKzLbNSxlw57sAOPIfEZshPpU1MNAym13jtg+3OoP/9MFWGwOTGjSFgCcSzb5kd5vBvbblAIqPfd73XZzOZHQQNVZXAYNtlvVv6dDcqAqmqwTr/omJMCX31A/hIaSUePyVcpFO720tbI/u4JnhU4IH9eIKVPUCOGun7YDCasrw6rd9PgYj7IR7OrfyjMjOvTOjyugelEIft/QNpGc2exs/Z6JitoFPJd5lp1shG7EyoPjlvm+58Jgzu34mbrgwrPYhGMjyTEaAErafbtSEyofkLMgtjrOnW5OYKUimDG6NUY7cwlHT/8RcXYs4ZuK3gf/JnbtPtmnzLvGaVxHf6O4Gktn3FGoRY8wsOn7q8EZ+2D6ehpGHbsUjQvy7bJTtk5jsDcSY2VYTwOwt2Sue7C2y4hxMGsR708ykVU7pYXlAO5t3nonlQw3b09NdBBvX0Hjo/ypQO6OtgRGJEG0bfdI0Qtr+h2gLR5ZDMrRvwR3WykaLEqSSbY2W6CDTRgRgOuxoSE52VO/KkbpImiLuEHwZ1HffLJ5BukQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-credentials
      namespace: database
