apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/name: postgresql
  name: postgresql-pvc
  namespace: database
spec:
  storageClassName: nfs-k8sdev-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem