---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio-storage
spec:
  storageClassName: nfs-k8sdev-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi