---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-ddns-secret
  namespace: cert-manager
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgC7p8opSy18Tf1Lp1Qa7zlPMCS+wMHV+sX2Uj3rsULkXrX1Gwaw4xsPU3Ryv9xc1SNcnRi4ivJQ8CUrOTCjFSBEk4IdfIHVtXsK+hqF7WJ4Nv9HqRlzHCtkpJ2dbh9xJ6RH8qp86FGOYKGK6jWZF2S/0mwCXas8oOSTXxiuPT8gMo0zLRyU0Bk9lM700bQqtaJhzGuC7XnUuKHM/OkIeElHEXh4FB/IYG5zDXqX8YJ1wxa5OQVtGVOkzKEi7rI58ZitK6VfY7nHdwwCr7phsA3CUlcNBXdXeIetCG1fsaddog4YpHZieQ3yT9iaplqXCZYNNhbDCH7Y34TpCSMN7HftzgBOrDFsYUroET61W54V7vOCFjIIRgZuVWKCQZb92NGo7AoGCkLfPOqwqc1QXCcF/sIGHn7jTDebFlqWAJ9S4rrwD0lDjmpfaPo+hKEgY+LXGfyS006ZYbQeDlxKyxWu5J1PBG+Q/aDGxJh8tisJd+NBjMzd8Cp71q+KrzjmsA5hDItryqoC2bgyY2I3ZfgwjwxU7Cu9bRTbm6Ky+G0va7RFSjBlZzpSTtVNCzYqih9giJYgTlPh8ePoJK5HaWBpRWTQo5zYSTpyGgV4IPF54MGddrmtNsAmAolBWKvXWZqhnTYtW9dkLHvEArHAcGrGi0rFeGR9A6+fHXcQlc0xIZswDnFSckD+GVEQemmfa0dwH3mWpCxVxq+vQEJxmYoqJATXyjox40b7ZqvGxY5qDFshAHz5V3ff
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-ddns-secret
      namespace: cert-manager
    type: Opaque
