repo:
  url: https://github.com/fkheinstein204/k8s-homelab.git
  revision: main

applications:

  - name: cert-manager
    namespace: cert-manager
    path: infrastructure/cert-manager
    manifest-paths: /infrastructure/cert-manager
    sync-wave: "0"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

  - name: ca-local-authority
    namespace: cert-manager
    path: infrastructure/ca-local-authority
    manifest-paths: /infrastructure/ca-local-authority
    sync-wave: "-5"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=false

  - name: cloudfare-dns
    namespace: cert-manager
    path: infrastructure/cloudfare-dns
    manifest-paths: /infrastructure/cloudfare-dns
    sync-wave: "-5"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

  - name: metallb
    namespace: metallb-system
    path: infrastructure/metallb
    manifest-paths: /infrastructure/metallb
    sync-wave: "-4"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

  - name: traefik
    namespace: traefik
    path: infrastructure/traefik
    manifest-paths: /infrastructure/traefik
    sync-wave: "-4"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

  - name: ingress-nginx
    namespace: ingress-nginx
    path: infrastructure/ingress-nginx
    manifest-paths: /infrastructure/ingress-nginx
    sync-wave: "-4"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

  - name: nfs-provisioner
    namespace: nfs-provisioner
    path: infrastructure/nfs-provisioner
    manifest-paths: /infrastructure/nfs-provisioner
    sync-wave: "-5"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

  - name: sealed-secrets
    namespace: kube-system
    path: infrastructure/sealed-secrets
    manifest-paths: /infrastructure/sealed-secrets
    sync-wave: "-5"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=false

  - name: longhorn
    namespace: longhorn-system
    path: infrastructure/longhorn
    manifest-paths: /infrastructure/longhorn
    sync-wave: "-5"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

  - name: minio
    namespace: minio-storage
    path: infrastructure/minio-s3
    manifest-paths: /infrastructure/minio-s3
    sync-wave: "-4"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

  - name: keycloak
    namespace: keycloak
    path: infrastructure/keycloak
    manifest-paths: /infrastructure/keycloak
    sync-wave: "-4"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true


  - name: hbr-keycloak
    namespace: hbr-keycloak
    path: infrastructure/hbr-keycloak
    manifest-paths: /infrastructure/hbr-keycloak
    sync-wave: "-4"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

  #- name: vault
  #  namespace: vault
  #  path: infrastructure/vault
  #  manifest-paths: /infrastructure/vault
  #  sync-wave: "-4"
  #  helm:
  #    enabled: true
  #  syncOptions:
  #    - CreateNamespace=true