---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: traefik
spec:
  encryptedData:
    api-token: AgBTyzdBh52t0mYBzVKHyIHQ7s5tWTT0A9dgO1bUpeiR+qMBKRUMt439Ke7zF0F4grE8wT41FFFCNAUBCzbgtW5g/6c8DDNpDSCHbToeTxtHNlLpE9g9ZeB5weHqXTVFKCliUOpAm5VlqOGxoYzwyD0hzxxrjGIQYYBERs1LpdlY5NZpAnwp3O8RwkqX3Idgvp06nix+XOIcDjU7qu4mVlFUMVCWv7VU0Isa2pcp97qjC/AXFEHogZdoIViW0bMlDr8cRzjrfmUTh6Db+K33FtwLnYQ+bWLaeI1mw00i6KRxurTffQxJ/CBgtWJwgU2/rCw7bTEwIEkIIOVfhnBXJZTVFYWT7GmCHkKaIbGHAv4BUvTQBsW0kHTtKGC3+0tSsYQb86Xu7pIpcdiKMHhibtE90gHsA8mTDEj/VUsk3ypTEXvidtDSg4cPnR2jv/0FDAm2oqe0aKYUTytW+BP7cV109TyUmTrlAuZKKEc+H14Qttoi5SBFATZ1edcuoKYxctTKdCubW5VpmBnloCCGyTCca3jGmDTJbsYSIy6rkgDQ8nV3AM1HabaJn8OsQ5mRAX40gfRamq+bJmehKGwYhWvFTjqYlXMqvNY/EHi9Ck7hycuezYYPuHtY2ksFhzzTuQ20EWavlfa/XKsGo9jGib+fnLJl0QlyzwO4+Bq9UCFPDoCYQ0wv+LK+RjnzQzNu+adVgpOCFhKXQVGAhHKXEW9qnWCYf2OrPhS7Qs8WLz2qzKr5tLasmaXn
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: traefik
    type: Opaque
