---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    api-token: AgCMa76YkIgXfhdqHmk8/D0PdUV5VPVwKW7xTQEpz/nhSJI26xz6GY7Jz8xcIGVZ9BVFx5jJe90jpw4KGfwtQ1Ks9KGzHcT3gOc3DgHRTwMfk44H9zAgj0jorjFg/BY93X5oMbRl0Tcw4PsYcaxoky+TyKf9duHVks1YYo1ohGq0b9+cWBagcc0JAiqccuIh4xC/+CUdZ4pkj+w5g3+6XXLKviUks+75IvB5Rjvh9A975IRYt1etOZIPbIkIABpj2lfVp5ghbftmhm2xcMQr+8x9v0K0J2XMi58ekFG7Fz/BSF7DHeTi595uMgOzkc/Ui4hHWaFGTRrHzoY//oUCtV/BpNnbAKmqDmCIcxOw6RaCSRP0/EZf+9eVbQDkXHu/R6Fn7qTnDf/XUzw9LX8bsGcxkLgcRXmN3jwXXW+7uX3moGSTqqj9WcFDSNUnh4EDAsfLdK1Bs6Aj5csydZ9tdkCIPTE24RYKtL1j43i9w2zN5feCQieXKHvgA7xMbMuqxLC8XmF7RLDDWTIrv82HfLZ5uV060tEXMrPaJDUn3Xr4iwk9kQk4TmCzPhrWNeRHOAzOhWshzNDGddrMGTXTeUYA9GfXecY3adjOo4x3YWb20QjQA+KTCgaG0yp3q3GPiLLGceUPp7jaZWvfc6IaEynWae3lYVhGmJOLCaMETpqfaKiSw1ZYsvxlTVuMkNcVeg89Kq75CKCkqx+bJhj+Ee9e0y6S7VIXiT1y77nt9xcaSLk16zxwz4cj
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: traefik
    type: Opaque
