apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-prod
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`traefik.homelab.ftscode.de`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService