postgresql:
  enabled: true
  auth:
    database: keycloak
    username: keycloak
    existingSecret: postgresql-credentials
    secretKeys:
      userPasswordKey: password
      adminPasswordKey: postgresql-password
      replicationPasswordKey: replication-password  # Required for replication
      existingSecret: postgresql-credentials

  architecture: replication

  primary:
    persistence:
      enabled: true
      existingClaim: postgresql-pvc
      size: 10Gi
    resources:
      requests:
        cpu: 1
        memory: 1Gi

  readReplicas:
    replicaCount: 1
    persistence:
      size: 10Gi

