postgresql:
  enabled: true

  clusterDomain: k8s-dev.devops.lab

  auth:
    enablePostgresUser: true
    replicationUsername: repl_user
    existingSecret: postgresql-credentials

  architecture: replication
  replication:
    synchronousCommit: "off"
    numSynchronousReplicas: 0

  primary:
    persistence:
      enabled: true
      existingClaim: postgresql-pvc
      size: "4Gi"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "512Mi"
        cpu: "500m"


  readReplicas:
    replicaCount: 2  # This gives us 3 nodes total (1 primary + 2 replicas)
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "512Mi"
        cpu: "500m"
    persistence:
      enabled: true
      existingClaim: postgresql-pvc
      size: "4Gi"