postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    replicationUsername: repl_user
    existingSecret: postgresql-credentials

  architecture: replication

  primary:
    persistence:
      enabled: true
      existingClaim: postgresql-pvc
      size: "4Gi"
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
      requests:
        memory: "256Mi"
        cpu: "200m"


  readReplicas:
    replicaCount: 2  # This gives us 3 nodes total (1 primary + 2 replicas)
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
      requests:
        memory: "256Mi"
        cpu: "200m"
    persistence:
      enabled: true
      existingClaim: postgresql-pvc
      size: "4Gi"