postgresql:
  enabled: true

  clusterDomain: k8s-dev.devops.lab

  auth:
    enablePostgresUser: true
    replicationUsername: repl_user
    existingSecret: postgresql-credentials

  architecture: standalone

  primary:
    persistence:
      enabled: true
      existingClaim: postgresql-pvc
      size: "4Gi"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "512Mi"
        cpu: "500m"

