postgresql:
  enabled: true
  auth:
    database: keycloak
    username: keycloak
    existingSecret: postgresql-credentials

  architecture: standalone

  primary:
    persistence:
      enabled: true
      existingClaim: postgresql-pvc
      size: 10Gi
  replication:
    enabled: true
    readReplicas: 2
  readReplicas:
    persistence:
      enabled: false
      size: 10Gi

