repo:
  url: https://github.com/fkheinstein204/k8s-homelab.git
  revision: main

applications:
  - name: argocd
    app-namespace: argocd
    project: default
    server: https://10.128.1.60:6443
    namespace: argocd
    path: argocd
    manifest-paths: /argocd
    sync-wave: "-5"

  - name: infrastructure
    namespace: argocd
    project: default
    server: https://10.128.1.60:6443
    path: infrastructure/
    manifest-paths: /infrastructure/templates;/infrastructure/Chart.yaml;/infrastructure/values.yaml
    sync-wave: "-4"

  - name: prod-infra
    namespace: argocd
    path: infrastructure/prod-cluster/
    manifest-paths: /infrastructure/prod-cluster/templates;/infrastructure/prod-cluster/Chart.yaml;/infrastructure/prod-cluster/values.yaml
    sync-wave: "-4"


  - name: database
    namespace: argocd
    path: database/
    manifest-paths: /database/templates;/database/Chart.yaml;/database/values.yaml
    sync-wave: "-4"


  - name: prod-monitoring
    namespace: argocd
    path: monitoring/prod-cluster/
    manifest-paths: /monitoring/prod-cluster/templates;/monitoring/prod-cluster/Chart.yaml;/monitoring/prod-cluster/values.yaml
    sync-wave: "-4"


  - name: dev-monitoring
    namespace: argocd
    path: monitoring/dev-cluster/
    manifest-paths: /monitoring/dev-cluster/templates;/monitoring/dev-cluster/Chart.yaml;/monitoring/dev-cluster/values.yaml
    sync-wave: "-4"


  - name: root
    app-namespace: argocd
    namespace: argocd
    path: apps
    manifest-paths: /apps