repo:
  url: git@github.com:fkheinstein204/k8s-homelab.git
  revision: main

applications:
  - name: argocd
    app-namespace: argocd
    project: default
    server: https://10.128.1.60:6443
    namespace: argocd
    path: infra/argocd
    manifest-paths: /argocd
    sync-wave: "-5"

  - name: infrastructure
    namespace: argocd
    path: infra/infrastructure/
    manifest-paths: /infrastructure/templates;/infrastructure/Chart.yaml;/infrastructure/values.yaml
    sync-wave: "-4"

  - name: root
    app-namespace: argocd
    namespace: argocd
    path: apps
    manifest-paths: /apps