---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-ftscode-prod-de
  namespace: cert-manager
spec:
  secretName: wildcard-ftscode-de-prod-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.ftscode.de"
  dnsNames:
  - "*.ftscode.de"