apiVersion: v2
name: keycloak
description: >
  A Helm chart to deploy Keycloak with Sealed Secrets and PostgreSQL HA on Kubernetes.
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: keycloak
  version: 24.4.13
  repository: https://charts.bitnami.com/bitnami