keycloak:
  global:
    storageClass: "nfs-k8sdev-client"

  auth:
    adminUser: admin
    existingSecret: keycloak-admin-password
    passwordSecretKey: admin-password

  production: true
  #proxy: edge
  # ref: https://www.keycloak.org/server/reverseproxy
  proxyHeaders: xforwarded

  externalDatabase:
    existingSecret: postgresql-keycloak-credentials
    host: "postgresql-primary-hl.database.svc.k8s-dev.devops.lab"
    port: 5432
    user: "keycloak"
    password: null
    existingSecretPasswordKey: password
    database: "keycloak"



  postgresql:
      enabled: false

  resources:
    limits:
      cpu: 2
      memory: "1Gi"
    requests:
      cpu: 1
      memory: "512Mi"