keycloak:
  global:
    storageClass: "nfs-k8sdev-client"

  auth:
    adminUser: admin
    existingSecret: keycloak-admin-password
    passwordSecretKey: admin-password

  production: true
  #proxy: edge
  # ref: https://www.keycloak.org/server/reverseproxy
  proxyHeaders: xforwarded

  externalDatabase:
    existingSecret: postgresql-keycloak-credentials
    host: "postgresql-primary-hl.database.svc.k8s-dev.devops.lab"
    port: 5432
    user: "keycloak"
    password: null
    existingSecretPasswordKey: password
    database: "keycloak"


  extraEnvVars:
    - name: KC_HOSTNAME
      value: "https://keycloak.homelab.ftscode.de"
    - name: KC_HOSTNAME_ADMIN
      value: "https://keycloak-admin.homelab.ftscode.de"
    - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
      value: "true"

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: keycloak.homelab.ftscode.de
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/common-name: keycloak.homelab.ftscode.de
    extraTls:
      - hosts:
          - keycloak.homelab.ftscode.de
        secretName: keycloak-cert

  adminIngress:
    enabled: true
    ingressClassName: nginx
    hostname: keycloak-admin.homelab.ftscode.de
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/common-name: keycloak-admin.homelab.ftscode.de
    extraTls:
      - hosts:
          - keycloak-admin.homelab.ftscode.de
        secretName: keycloak-admin-cert


  postgresql:
      enabled: false

  resources:
    limits:
      cpu: 2
      memory: "1Gi"
    requests:
      cpu: 1
      memory: "512Mi"