keycloak:
  global:
    storageClass: "nfs-k8sdev-client"

  clusterDomain: k8s-dev.devops.lab

  auth:
    adminUser: admin
    existingSecret: keycloak-admin-password
    passwordSecretKey: admin-password

  production: true
  #proxy: edge
  # ref: https://www.keycloak.org/server/reverseproxy
  proxyHeaders: xforwarded

  extraEnvVars:
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: admin-password
          name: keycloak-admin-password
    - name: KC_PROXY
      value: "edge"
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KC_METRICS_ENABLED
      value: "true"
    - name: KC_HOSTNAME_STRICT_HTTPS
      value: "true"
    - name: KC_LOG_LEVEL
      value: INFO


  externalDatabase:
    existingSecret: postgresql-keycloak-credentials
    host: "postgresql-primary-hl.database.svc.k8s-dev.devops.lab"
    port: 5432
    user: "keycloak"
    password: null
    existingSecretPasswordKey: password
    database: "keycloakdb"

  postgresql:
      enabled: false

  resources:
    limits:
      cpu: 2
      memory: "1Gi"
    requests:
      cpu: 1
      memory: "512Mi"