repo:
  url: https://github.com/fkheinstein204/k8s-homelab.git
  revision: main


applications:

  - name: grafana
    namespace: grafana
    path: monitoring/dev-cluster/grafana
    manifest-paths: /monitoring/dev-cluster/grafana
    sync-wave: "-1"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true

  - name: metrics-server-dev
    namespace: metrics-server
    path: monitoring/dev-cluster/metrics-server
    manifest-paths: /monitoring/dev-cluster/metrics-server
    sync-wave: "-1"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true      