redis:
  architecture: replication
  auth:
    enabled: true
    sentinel: true
    existingSecret: redis-credentials
  master:
    count: 1
    disableCommands:
      - FLUSHDB
      - FLUSHALL
    persistence:
      enabled: false
  replica:
    replicaCount: 3
    disableCommands:
      - FLUSHDB
      - FLUSHALL
    persistence:
      enabled: false
  image:
    registry: docker.io
    pullPolicy: IfNotPresent
  sentinel:
    enabled: false
    persistence:
      enabled: false
    image:
      registry: docker.io
      pullPolicy: IfNotPresent
  metrics:
    enabled: false
    image:
      registry: docker.io
      pullPolicy: IfNotPresent
  volumePermissions:
    enabled: false
    image:
      registry: docker.io
      pullPolicy: IfNotPresent
  sysctl:
    enabled: false
    image:
      registry: docker.io
      pullPolicy: IfNotPresent