redis:
  global:
    storageClass: "nfs-k8sdev-client"

  auth:
    enabled: true
    sentinel: true
    existingSecret: "redis-credentials"

  architecture: replication  # Enables master-replica setup

  master:
    persistence:
      enabled: true
      storageClass: "nfs-k8sdev-client"
      size: 5Gi
    service:
      type: ClusterIP

  replica:
    replicaCount: 3
    persistence:
      enabled: true
      storageClass: "nfs-k8sdev-client"
      size: 5Gi
    service:
      type: ClusterIP

  sentinel:
    enabled: true
    persistence:
      enabled: true
      storageClass: "nfs-k8sdev-client"
      size: 2Gi