redis:
  global:
    storageClass: "nfs-k8sdev-client"

  auth:
    enabled: true
    existingSecret: "nfs-k8sdev-client"

  architecture: replication  # Enables master-replica setup

  master:
    persistence:
      enabled: true
      storageClass: "nfs-k8sdev-client"
      size: 5Gi
    service:
      type: ClusterIP

  replica:
    replicaCount: 2
    persistence:
      enabled: true
      storageClass: "nfs-k8sdev-client"
      size: 5Gi
    service:
      type: ClusterIP