---
apiVersion: v2
name: nginx-ingress-controller
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: ingress-nginx
  version: 4.12.0
  repository: https://kubernetes.github.io/ingress-nginx